version: '3.8'

services:
  shap-api:
    image: shap-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shap-api
    environment:
      - CLOUDINARY_NAME=*********8 
      - API_KEY=*********** 
      - API_SECRET=**************
    ports:
      - '5000:5000'
    restart: always

networks:
  default:
    external:
      name: bridge
